version: '3.7'

services:
  bps-internal-tools:
    build:
      context: .
      args:
        GIT_COMMIT: ${GIT_COMMIT}
        GIT_VERSION: ${GIT_VERSION}
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_CREDENTIALS_PATH=${GOOGLE_CREDENTIALS_PATH}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ${LOCAL_GOOGLE_CREDENTIALS_PATH}:${GOOGLE_CREDENTIALS_PATH}
      - ${LOCAL_DATA_PATH}:/app/data
      - ./env:/app/env  # Mount the CSV files into the container

